name: Publish WebApi

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - 'live'
    paths:
      - 'src/UCLL.Projects.WeatherStations.WebApi/**'
      - 'src/UCLL.Projects.WeatherStations.Shared/**'

permissions:
  contents: read

jobs:
  build-publish_webapi:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/UCLL.Projects.WeatherStations.WebApi/Dockerfile
          push: true
          tags: |
            docker.io/weatherstations/ucll.projects.weatherstations.webapi:latest
            docker.io/weatherstations/ucll.projects.weatherstations.webapi:${{ github.sha }}
      - # good practice (for when multiple jobs)
        name: Log out from Docker Hub
        run: docker logout
